services:
  mongo:
    container_name: mongo
    image: mongo:4.4.27
    environment:
      MONGODB_CLIENT_EXTRA_FLAGS: "--authenticationDatabase admin"
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
networks:
  mysql_cluster:
    driver: bridge
